name: CI

# Define when the workflow should run
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Install CMake, Bison, and Flex
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake bison flex libfl-dev

    # Cache the build directory to speed up builds
    - name: Cache CMake build
      uses: actions/cache@v2
      with:
        path: build
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt', '**/*.l', '**/*.y') }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    # Run the build script
    - name: Run build script
      run: ./build.sh

    # Run tests
    - name: Run tests
      run: ./test.sh
